# Generated by Django 4.1.3 on 2023-01-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding_finch_alter_feeding_date_alter_feeding_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
            ],
        ),
    ]
